### ISSUE TITLE
utils: GenerateSecureToken uses a pseudo-random generator which isn't advised for secure and cryptographic purposes, moreover with a predictable seed of time.Now().UnixNano() and on the global reader

### ISSUE THREAD

**Issue by odeke-em** [lum-network/chain#73]
While examining this repository for security issues, I noticed that the code for GenerateSecureToken 

https://github.com/lum-network/chain/blob/4f801b06afc59823d65fdacfaa1a35d60089e50c/utils/strings.go#L13-L19

uses a pseudo-random generator in math/rand of which even the GoDoc for the package explicitly says https://pkg.go.dev/math/rand ![image](https://github.com/lum-network/chain/assets/4898263/ede9f963-f206-4571-95d9-fe3338a78a9b) and even if seeded, its outputs can be predicted 

Even more, this code uses the global reader with a very weak seed of time.Now().UnixNano() which an attacker can properly trivially find; also it mutates the global pseudo-random reader which makes for even worse predictable state.

This can be a serious security issue.

## Suggestion
Please use a stronger source of randomness like crypto/rand and just invoke crypto/rand.Read(seed) 

/cc @elias-orijtech @veorq

**Comment by Segfaultd** [comment]
Thanks for the issue. It is only used in unit tests, not in production code. Thus i'm closing the issue and won't fix.

**Comment by odeke-em** [comment]
@Segfaultd I highly encourage that you delete that code or change the name to remove alluding to it being "secure" because people import libraries blindly without examining the source code
